# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

# Mouse mode
set -g mouse on

# Better prefix
set -g prefix C-a

# Vim-style pane navigation (prefix + h/j/k/l)
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Unbind old tmux copy commands
unbind-key -T copy-mode-vi v

# Tmux copy commands
setw -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection     # Begin selection in copy mde.
bind-key -T copy-mode-vi 'C-v' send -X rectangle-toggle  # Begin selection in copy moe.
bind-key -T copy-mode-vi 'y' send -X copy-selection      # Yank selection in copy mode

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
